#!/bin/sh

[ -d /dev ] || /bin/busybox mkdir -m 0755 /dev
[ -d /root ] || /bin/busybox mkdir -m 0700 /root
[ -d /sys ] || /bin/busybox mkdir /sys
[ -d /proc ] || /bin/busybox mkdir /proc
[ -d /tmp ] || /bin/busybox mkdir /tmp
/bin/busybox mkdir -p /var/lock
/bin/busybox mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
/bin/busybox mount -t proc -o nodev,noexec,nosuid proc /proc

/bin/busybox ln -s /proc/self/fd/0 /dev/stdin
/bin/busybox ln -s /proc/self/fd/1 /dev/stdout
/bin/busybox ln -s /proc/self/fd/2 /dev/stderr

export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin

/bin/busybox echo "##############################################################################"
/bin/busybox echo "#                                                                            #"
/bin/busybox echo "#    PiNAS GNU/Linux                                                         #"
/bin/busybox echo "#    Copyright (C) 2013 Juan Antonio Nache <ja@nache.net>                    #"
echo "#                                                                            #"
echo "#    This program is free software: you can redistribute it and/or modify    #"
echo "#    it under the terms of the GNU General Public License as published by    #"
echo "#    the Free Software Foundation, either version 3 of the License, or       #"
echo "#    (at your option) any later version.                                     #"
echo "#                                                                            #"
echo "#    This program is distributed in the hope that it will be useful,         #"
echo "#    but WITHOUT ANY WARRANTY; without even the implied warranty of          #"
echo "#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           #"
echo "#    GNU General Public License for more details.                            #"
echo "#                                                                            #"
echo "#    You should have received a copy of the GNU General Public License       #"
echo "#    along with this program.  If not, see <http://www.gnu.org/licenses/>.   #"
echo "#                                                                            #"
echo "##############################################################################"


echo "Loading PiNAS..."

#Create all the symlinks to /bin/busybox
busybox --install -s

date

#Create device nodes
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s


mount -t devtmpfs -o size=$tmpfs_size,mode=0755 udev /dev ||  mount -t tmpfs -o size=$tmpfs_size,mode=0755 udev /dev
[ -e /dev/console ] || mknod -m 0600 /dev/console c 5 1
[ -e /dev/null ] || mknod /dev/null c 1 3
mkdir /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
mount -t tmpfs -o "nosuid,size=20%,mode=0755" tmpfs /run
mkdir -m 0755 /run/initramfs
mkdir /media/
mount /dev/mmcblk0p1 /media

get_opt() {
	echo "$@" | cut -d "=" -f 2
}

init="/sbin/init"
rootmnt="/target

for i in $(cat /proc/cmdline); do
	case $i in
		root\=*)
			rootmnt=$(get_opt $i)
			;;
		init\=*)
			init=$(get_opt $i)
			;;
	esac
done

#Here we mount squaskfs root on /target
mount -o loop -t squashfs /media/rootfs.sqfs "${rootmnt}"

mount -n -o move /sys ${rootmnt}/sys
mount -n -o move /proc ${rootmnt}/proc

exec busybox switch_root ${rootmnt} ${init} "$@" <${rootmnt}/dev/console >${rootmnt}/dev/console
busybox switch_root ${rootmnt} "${init}"

echo "[E] Error switching to squashfs root"
