#!/bin/sh
##############################################################################
#
#    PiNAS GNU/Linux
#    Copyright (C) 2013 Juan Antonio Nache <ja@nache.net>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
############################################################################


echo "##############################################################################
echo "#                                                                            #
echo "#    PiNAS GNU/Linux                                                         #
echo "#    Copyright (C) 2013 Juan Antonio Nache <ja@nache.net>                    #
echo "#                                                                            #
echo "#    This program is free software: you can redistribute it and/or modify    #
echo "#    it under the terms of the GNU General Public License as published by    #
echo "#    the Free Software Foundation, either version 3 of the License, or       #
echo "#    (at your option) any later version.                                     #
echo "#                                                                            #
echo "#    This program is distributed in the hope that it will be useful,         #
echo "#    but WITHOUT ANY WARRANTY; without even the implied warranty of          #
echo "#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           #
echo "#    GNU General Public License for more details.                            #
echo "#                                                                            #
echo "#    You should have received a copy of the GNU General Public License       #
echo "#    along with this program.  If not, see <http://www.gnu.org/licenses/>.   #
echo "#                                                                            #
echo "##############################################################################

echo "Loading PiNAS..."
mount -t proc -o nodev,noexec,nosuid proc /proc
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys

#Create all the symlinks to /bin/busybox
busybox --install -s

#Create device nodes
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s
mkdir /root


mount -t devtmpfs -o size=$tmpfs_size,mode=0755 udev /dev ||  mount -t tmpfs -o size=$tmpfs_size,mode=0755 udev /dev
[ -e /dev/console ] || mknod -m 0600 /dev/console c 5 1
[ -e /dev/null ] || mknod /dev/null c 1 3
mkdir /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
mount -t tmpfs -o "nosuid,size=20%,mode=0755" tmpfs /run
mkdir -m 0755 /run/initramfs

get_opt() {
	echo "$@" | cut -d "=" -f 2
}

init="/sbin/init"
rootmnt="/target

for i in $(cat /proc/cmdline); do
	case $i in
		root\=*)
			rootmnt=$(get_opt $i)
			;;
		init\=*)
			init=$(get_opt $i)
			;;
	esac
done

#Here we mount squaskfs root on /target
mount "${rootmnt}" /target

mount -n -o move /sys ${rootmnt}/sys
mount -n -o move /proc ${rootmnt}/proc

exec busybox switch_root ${rootmnt} ${init} "$@" <${rootmnt}/dev/console >${rootmnt}/dev/console
busybox switch_root /target "${init}"

echo "[E] Error in switching from initrd to root fs"
